### ISSUE TITLE
Прекрасный тест..

### ISSUE THREAD

**Issue by Fodense** [ykuzma/cleverTask2-2#1]
https://github.com/ykuzma/cleverTask2-2/blob/48cb3e25a47358a3325b4c5138161fc6aa490f03/api/src/test/java/ru/clevertec/api/AppTest.java#L11

**Comment by ykuzma** [comment]
Уточни, пожалуйста, как закрываются issues - я исправляю, пушу изменения, ты проверяешь и закрываешь? 
В данном случае достаточно удалить "прекрасный" тест?

**Comment by ykuzma** [comment]
Написал новые тесты.
 Логику из main вынес в отдельный метод, передал экземпляр Utils в качестве параметра и сделал isAllPositiveNumber non-static, чтобы замокать в тесте.

    @ParameterizedTest
    @MethodSource
    void shouldReturnCorrectString(String[] numbers, String expectedString, boolean mockReturn) {
        Utils util = Mockito.mock(Utils.class);
        when(util.isAllPositiveNumbers(numbers)).thenReturn(mockReturn);


        String actual = App.checkIsNumberPositive(util, numbers);
        assertEquals(expectedString, actual);
    }
