### ISSUE TITLE
Кастомный эксепшен

### ISSUE THREAD

**Issue by Fodense** [ykuzma/cleverTask2-2#2]
За кастомный эксепшен конечно лайк, но можно было бы и уже существуюбшим обойтись

https://github.com/ykuzma/cleverTask2-2/blob/48cb3e25a47358a3325b4c5138161fc6aa490f03/core/src/main/java/ru/clevertec/core/InputDataException.java#L3

**Comment by Fodense** [comment]
И тогда бы тут отлавливала только один api/src/main/java/ru/clevertec/api/App.java , а не свой и плюс существующий

**Comment by ykuzma** [comment]
> За кастомный эксепшен конечно лайк, но можно было бы и уже существуюбшим обойтись
> 
> https://github.com/ykuzma/cleverTask2-2/blob/48cb3e25a47358a3325b4c5138161fc6aa490f03/core/src/main/java/ru/clevertec/core/InputDataException.java#L3

Существующий - это IllegalArgumentException?

**Comment by ykuzma** [comment]
Заменил кастомный на IllegalArgumentException
